GROUP_REPOS = [
    [
        "group a",
        "ZeroDownTime",
        ["https://github.com/ZeroDownTime-ITU/minitwit_project"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "catch(RuntimeException){goto f;}",
        ["https://github.com/JohannesHackl/DevOps26_RE_minitwit"],
        "http://164.92.186.201:5001",
        "http://164.92.186.201:5001/api",
    ],
    [
        "group c",
        "group c",
        ["https://github.com/jskoven/Devops2026_jklo_jakst_aing_asjo_mbln"],
        "http://161.35.68.148:5001",
        "http://161.35.68.148:5001",
    ],
    [
        "group d",
        "Dense Dino Nuggets",
        ["https://github.com/Slug-Boi-ITU-Repositories/Dense-Dino-Nuggets"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "Jams",
        ["https://github.com/sebsthiel/minitwit-devops"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "if time > 16 {beer++;}",
        ["https://github.com/TienCamLy/MiniTwit"],
        "http://157.230.30.175:8080",
        "http://157.230.30.175:8080",
    ],
    [
        "group g",
        "DevOpps",
        ["https://git.marfavi.com/DevOpps/itu-minitwit-migration"],
        "https://minitwitter.com",
        "https://minitwitter.com",
    ],
    [
        "group i",
        "I Terroni",
        ["https://github.com/stegish/I-Terroni-DevOps"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group k",
        "Pat Myaz",
        ["https://github.com/ITU-DevOps2026/ITU-minitwit"],
        "http://209.38.114.224:5035",
        "http://209.38.114.224:5035/api",
    ],
    [
        "group m",
        "Holy C Enjoyers",
        ["https://github.com/MudiLoodi/minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "Diversity",
        ["https://github.com/huncut47/diversity"],
        "http://168.119.126.80",
        "http://168.119.126.80",
    ],
    [
        "group o",
        "Rollback & Relax",
        ["https://github.com/alqeren1/devops"],
        "http://ec2-13-51-198-31.eu-north-1.compute.amazonaws.com:3000",
        "http://ec2-13-51-198-31.eu-north-1.compute.amazonaws.com:3000",
    ],
    [
        "group a",
        "EastTops",
        ["https://github.com/AntohaY/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group q",
        "DevTroopers",
        ["https://github.com/DevTroopers-ITU/itu-minitwit"],
        "http://46.224.144.214:8080",
        "http://46.224.144.214:8080",
    ],
]
